### ISSUE TITLE
Make sure people are logged in

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/wiki#1]
There exists a Header injection I have plugged into the `LocalSettings.php` file.

The aims to make sure that the user is logged in using jQuery or some other tool. If the response from `https://api.tnyu.org/v2/people/me` is 200 OK then the user is logged in.

Also make sure they have some team permissions.

If not then it has to be redirected to be logged in.

**Comment by AbhiAgarwal** [comment]
This is vital to exist at some point. When we put up our thoughts/relationships with companies.

**Comment by ethanresnick** [comment]
Also, for security, this needs to be verified on the server-side, rather than just on the client.

**EDIT**: More importantly, though, let's make sure mediawiki is right from a design POV before we spend time making technical changes to it. For now, therefore, I'd say the calendar service is actually higher priority (even though having a wiki is of course higher priority in the long run.)

**Comment by AbhiAgarwal** [comment]
It's PHP code ethan c'mon. Agreed, but this is server-side :(

**Comment by AbhiAgarwal** [comment]
@ethanresnick How do you propose to do this on server-side? I just read this not in a state of sleep.. Server-side meaning on the API side?

**Comment by ethanresnick** [comment]
Server-side meaning, probably, on the server that the wiki's running on. Because we can't do something that can be bypassed just by disabling javascript, which is what I thought you were talking about initially when you mentioned jquery.

Real integration with the API might be a pain, so I wonder: what's the dumbest thing that could possibly work? Maybe, just giving all of our boardmembers a username/password for the wiki, turning on http [digest authentication](http://en.wikipedia.org/wiki/Digest_access_authentication), and using [this](http://www.mediawiki.org/wiki/Extension:Auth_remoteuser)?

**Comment by AbhiAgarwal** [comment]
@ethanresnick +1. I found kind of a good solution too. Exactly something you proposed. I tried those methods, and they worked well as well. I'll try this one because I think it's somewhat better.

**Comment by AbhiAgarwal** [comment]
I'm going to close this for now as this is dealt with. Will re-open if I come up with a better solution over the summer.
